apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cabalcorp-rs
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      env: development
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        env: development
    spec:
      containers:
        - name: nginx
          image: nginx