apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
    labels:
        app: nginx-rc
        type: front-end-rc
spec:
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx
                type: front-end
        spec:
            containers:
              - name: nginx-controller
                image: nginx

