
name: ActionsTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DANTEKUBE

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Deploy inside GH Folder
      uses: actions-hub/kubectl@master 
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ./.github/workflows/nested/namespace.yml

    - name: Deploy OUTSIDE
      uses: actions-hub/kubectl@master 
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ./K8S/deployments/namespace.yml